### ISSUE TITLE
StackOverflowError with latest AutoHashEquals

### ISSUE THREAD

**Issue by tkelman** [andrewcooke/ParserCombinator.jl#14]
from PackageEvaluator: http://pkg.julialang.org/logs/ParserCombinator_0.4.log
and also Travis, if you trigger a new build: https://travis-ci.org/tkelman/ParserCombinator.jl/builds/105584168

**Comment by andrewcooke-isti** [comment]
oh, interesting.  thanks.

**Comment by andrewcooke** [comment]
this should be fixed by latest release (1.7.6)
