### ISSUE TITLE
× or * instead of +?

### ISSUE THREAD

**Issue by TotalVerb** [andrewcooke/ParserCombinator.jl#17]
Firstly, thanks for this package! I'm playing around with it and it's exceptionally easy to use :+1:.

This is a very minor matter (as it's just syntax), but it seems the `Seq` combinator used here is a Cartesian product (correct me if I'm wrong). Consequently, wouldn't `*` or `×` be a more natural choice of symbols? What are your thoughts?

**Comment by andrewcooke** [comment]
i don't have a great background in these things, but my understanding is that julia is going the other way.  the current docs don't even mention `*` for string concatenation.  and see https://github.com/JuliaLang/julia/issues/11030

honestly, i think it's going to confuse more people than it will help.  sorry.
