### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by andrewcooke** [andrewcooke/ParserCombinator.jl#25]
If anyone wants write access, or wants to fork and take over this package (I don't know how Julia supports that) please contact me.  I am very unlikely to be supporting this in the near/medium term.  Sorry.

@sbromberger @CarloLucibello @oxinabox @TotalVerb

**Comment by sbromberger** [comment]
So, is this effort abandoned? We're running into deprecation warnings and some issues with the DOT parser (see https://github.com/JuliaGraphs/GraphIO.jl/issues/5). If it is (and it'd be a shame!), then I guess we'll look at removing our dependence on it.

**Comment by oxinabox** [comment]
Looks like we're doing this
https://github.com/andrewcooke/ParserCombinator.jl/pull/27#issuecomment-349592293

**Comment by andrewcooke** [comment]
thanks - i've sent invites to @oxinabox and @CarloLucibello
