### ISSUE TITLE
Can't test GML

### ISSUE THREAD

**Issue by sbromberger** [andrewcooke/ParserCombinator.jl#3]
Getting

```
ERROR: LoadError: LoadError: UndefVarError: Parsers not defined
```

on `Pkg.test("ParserCombinator")`. Not sure how to import `ParserCombinator.Parsers.GML`.

It may have to do with the fact that some OSes (like OSX) are case-insensitive, and you've got both `Parsers.jl` and `parsers.jl`.

ETA: confirmed - when I rename parsers.jl we're all good.

**Comment by andrewcooke** [comment]
thanks, i'll fix that.

**Comment by andrewcooke** [comment]
ok, rearranged source.
