### ISSUE TITLE
Wrong Floating number regex

### ISSUE THREAD

**Issue by guyvdbroeck** [andrewcooke/ParserCombinator.jl#31]
The current implementation
```PFloat32() = Parse(p"-?(\d*\.?\d+|\d+\.\d*)([eE]\d+)?", Float32)
PFloat64() = Parse(p"-?(\d*\.?\d+|\d+\.\d*)([eE]\d+)?", Float64)
```
is missing the optional sign for the exponent: `"-?(\d*\.?\d+|\d+\.\d*)([eE]-?\d+)?"`
An implementation of PFloat16 is also missing.

**Comment by richardreeve** [comment]
@oxinabox - could you add me as a collaborator on this repo so I can add a PR to fix this?

**Comment by oxinabox** [comment]
no, but you are welcome to make a pull request.

**Comment by richardreeve** [comment]
I can't make a branch in the repo to make a PR because I don't have permission. Do you really want me to fork it and make a PR from my own repo? I'm not asking for permissions to actually merge anything.

**Comment by oxinabox** [comment]
> Do you really want me to fork it and make a PR from my own repo?

Yes.

**Comment by richardreeve** [comment]
Okay, you can close this now btw.
