### ISSUE TITLE
Alternative? Maintenance?

### ISSUE THREAD

**Issue by ctzurcanu** [andrewcooke/ParserCombinator.jl#34]
Is there an alternative to this or any will to make this work with current Julia?

The Example yields:

┌ Info: Precompiling ParserCombinator [fae87a5f-d1ad-5cf0-8f61-c941e1580b46]
└ @ Base loading.jl:1260
syntax: extra token "Node" after end of expression

**Comment by whilo** [comment]
I would be interested in this as well.

**Comment by ysaereve** [comment]
I tested the example (https://github.com/andrewcooke/ParserCombinator.jl#example) just now. It works. 

Julia Version: 1.8.1 (2022-09-06)

**Comment by ctzurcanu** [comment]
If you say it works, I will close this issue. (I have no time to verify and I trust you.)
