### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by sbromberger** [andrewcooke/ParserCombinator.jl#4]
```
ERROR: OverflowError()
 in parse_raw at /Users/seth/dev/julia/tempwip/ParserCombinator/src/gml/GML.jl:74
```

using http://www-personal.umich.edu/~mejn/netdata/polblogs.zip - 85k lines, but only 1490 nodes and 19091 edges.

**Comment by andrewcooke** [comment]
latest git has a fix for this.  the background is at https://groups.google.com/forum/#!topic/julia-users/mxbwCVfX_44

i should document the workaround, so will leave this open for now.

**Comment by andrewcooke** [comment]
ok, better fix auto-detects the use of vcat and does something more efficient.  so grammars can stay the same as before.
